telegram:
  api-token: ${TELEGRAM_API_TOKEN}
mqtt:
  domain: "mqtt.flynny2j.com" # IP/NAME of the MQTT Server 
  port: 8883
  protocol: "MQTTv311" # Either "MQTTv31" or "MQTTv311"
  username: ${MQTT_TELE_USERNAME}
  password: ${MQTT_TELE_PASS}
  topic: "telebot"
  keepalive: 60
webserver:
  domain: "192.168.1.500" # IP of where the webserver is reachable by the Mediaplayer in HA
  port: 8000
other:
  loglevel: 3
  # 1: Error Only, 2: Warning, 3: Info, 4: Debug
allowed_contacts:
  # user id: Display Name
  # Only listed Contacts are allowed to send voice messages
  377218764: "Rpodcast"
